/Stalknik:
  node_img_processing:
    ros__parameters:
      my_yolo_file: "file:///Users/rikic/Documents/Projet/Stalknik_MK2/ros_stalknik/src/img_processing/resource/yolo.h5"
      my_trained_model: "C:/Users/rikic/Documents/Projet/Stalknik_MK2/Cozmo_follow_car/trained_carmodel/car_cozmo.pt"
      IsCustom: True
/Stalknik:
  node_img_acquisition:
    ros__parameters:
      IsTest : True
      my_video_file : "file:///Users/rikic/Documents/Projet/Stalknik_MK2/PFE_video/outpy2.avi"

